steps:
  - name: 'gcr.io/cloud-builders/gradle'
    id: 'buildJar'
    args: ['build']
    dir: 'application'
    volumes:
      - name: 'jar'
        path: /jar
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args: ['build', '-t', 'gcr.io/development-271408/cloud-run-test:$SHORT_SHA', '.']
    dir: 'application'
    volumes:
      - name: 'jar'
        path: /jar
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args: ['push', 'gcr.io/development-271408/cloud-run-test:$SHORT_SHA']
  #  - name: 'gcr.io/cloud-builders/gcloud'
  #    id: 'deployToFunc'
  #    args: ['beta', 'run', 'deploy', 'cloud-run-test-func', '--image=gcr.io/pipeline-dev-271314/cloud-run-test:$SHORT_SHA', '--region=us-central1', '--platform=managed']
  #  - name: 'gcr.io/cloud-builders/mvn'
  #    id: 'functional-tests'
  #    args: ['verify', '-Dtest=com.example.helloworld.RunFuncTest']
  #    dir: 'cucumber-tests'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'tagImage'
    args: ['container', 'images', 'add-tag',  'gcr.io/development-271408/cloud-run-test:$SHORT_SHA', 'gcr.io/prod-271408/cloud-run-test:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deployToInt'
    args: ['beta', 'run', 'deploy', 'cloud-run-test', '--image=gcr.io/prod-271408/cloud-run-test:$SHORT_SHA', '--region=us-central1', '--platform=managed', '--project=prod-271408' ]
  - name: 'gcr.io/cloud-builders/gradle'
    id: 'tests'
    args: ['localFunctionalTests']
    dir: 'cucumber-tests'